name: code_scan
description: A flexible code scanner for qr, barcodes and others.
version: 0.0.1
homepage: https://github.com/DrafaKiller/CodeScan-dart

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.27.3
  camera: ^0.9.6
  google_mlkit_barcode_scanning: ^0.3.0
  thread: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
