name: code_scan
description: A flexible code scanner for QR codes, barcodes and many others. Using Google's ML Kit. Use it as a Widget with a camera or use the methods provided, with a camera controller.
version: 0.4.8
repository: https://github.com/DrafaKiller/CodeScanner-flutter
issue_tracker: https://github.com/DrafaKiller/CodeScanner-flutter/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.1
  google_mlkit_barcode_scanning: ^0.5.0
  rxdart: ^0.27.4

dev_dependencies:
  flutter_lints: ^2.0.1
